### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by beatgammit** [zorgnax/libtap#18]
I submitted [libtap to the AUR](https://aur.archlinux.org/packages/libtap-git/), but I didn't know what the version of this library was so I made one up. It would help a lot if you would tag releases so they show up under "Releases" on github: `git tag 0.1.0` or `git tag v0.1.0`. If you do that, I can make another PKGBUILD that targets released versions instead of development versions.

If my pull request (#17) is acceptable, I'll switch [my PKGBUILD](https://aur.archlinux.org/packages/libtap-git/) to point to this repository instead of my fork.

**Comment by zorgnax** [comment]
Thanks a lot. I tagged it as 0.1.0.

**Comment by beatgammit** [comment]
@zorgnax 

Thanks! In the future, could you make it an annotated tag? (`git tag -a 0.1.0`)

Annotated tags work with `git describe` by default, whereas 'lightweight` tags made with `git tag 0.1.0` don't (have to use `git describe --tag`). I just learned about the [difference](http://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags), so I apologize for not mentioning when I filed the issue.

I've accounted for it, but it might be nice to do in the future so it works for more people out-of-the-box.

**Comment by zorgnax** [comment]
ok. I just used the tagging that github provides.
