### ISSUE TITLE
make check fails without make install

### ISSUE THREAD

**Issue by loreb** [zorgnax/libtap#19]
The INSTALL file says to run make,make check, make install.

On a system without this library installed, try
 $ sh -c 'git clone http://github.com/zorgnax/libtap && cd libtap &&  make && make check'
 # all tests fail because libtap.so can't be found
 $ cd libtap && LD_LIBRARY_PATH=$PWD make check
 # all tests work

The easiest way imho is to run the tests using the static library

**Comment by zorgnax** [comment]
Thanks for pointing that out. I changed the makefile to compile against the static library.
