### ISSUE TITLE
exit_status()

### ISSUE THREAD

**Issue by loreb** [zorgnax/libtap#20]
I had some time to waste today...

exit(failed_tests) & similar are not ok - C11 says you can exit(EXIT_SUCCESS) or exit(EXIT_FAILURE), unix&windows have been using only the low byte since forever (see posix/msdn), meaning that eg a program that calls "exit(256)" appears to have succeeded (tried just now on linux).

I thought that exit codes>128 mean "killed by signal", but apparently I misremembered.

Only affects testsuites with >255 failures (or a number of failures that's a multiple of 256, which is funnier), but anyway... return min(retval,255)

**Comment by zorgnax** [comment]
Thanks for catching that. I changed the return value to 0 success, 1 failure, 2 missing tests, and done away with the number of failed tests, which wasn't useful anyway.
