### ISSUE TITLE
Consider change or add LGPL as license?

### ISSUE THREAD

**Issue by quentusrex** [zorgnax/libtap#21]
Any chance to update the existing license, or to dual license to something compatible with GPL and non-GPL? Such as:
https://www.gnu.org/licenses/lgpl.html
or
https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html

Right now a piece of software that is licensed with MPL can't use libtap for testing framework. Moving, or adding an LGPL license should solve the issue for the full spectrum of software projects.

**Comment by zorgnax** [comment]
LGPL it is!
