### ISSUE TITLE
plan is no more

### ISSUE THREAD

**Issue by allanwind** [zorgnax/libtap#24]
The synopsis says plan(5), however, that function appears to be called plan_tests().

**Comment by zorgnax** [comment]
the function is supposed to be plan(). where does it say plan_tests()?

**Comment by allanwind** [comment]
On 2015-08-28 08:22:42, Jacob Gelbman wrote:
> the function is supposed to be plan(). where does it say plan_tests()?

The header file has plan_tests() and there is no plan().


/Allan
-- 
Allan Wind
Yaxto - Runs My Business
<https://yaxto.com>

**Comment by zorgnax** [comment]
are you looking at a different file then this: https://github.com/zorgnax/libtap/blob/master/tap.h ???

**Comment by allanwind** [comment]
Sorry, it looks like I confused your tap implementation with anther that I was looking at.

**Comment by zorgnax** [comment]
Always use MY tap library :)

**Comment by allanwind** [comment]
On 2015-08-30 18:08:50, Jacob Gelbman wrote:
> Always use MY tap library :)

<https://theory.github.io/mytap/>? :-)



/Allan
-- 
Allan Wind
Yaxto - Runs My Business
<https://yaxto.com>

**Comment by zorgnax** [comment]
exactly
