### ISSUE TITLE
ok says "the test can be any statement returning a true or false value"

### ISSUE THREAD

**Issue by allanwind** [zorgnax/libtap#25]

**Comment by allanwind** [comment]
This may be more of a question than anything. 

The first test I wrote was ok(s = server_init()) where server_init returns an opaque pointer.  This fails, with:

allan@vent:~/src/yaxto$ make check
cc -g -I~/include -I. -Wall   -c -o t/server.o t/server.c
In file included from t/server.c:2:0:
t/server.c: In function ‘main’:
t/server.c:8:5: warning: passing argument 3 of ‘ok_at_loc’ makes integer from pointer without a cast
  ok(s = server_init());
     ^
/home/allan/include/tap.h:48:56: note: in definition of macro ‘ok’
 #define ok(...)          ok_at_loc(__FILE__, __LINE__, __VA_ARGS__, NULL)
                                                        ^
/home/allan/include/tap.h:28:9: note: expected ‘int’ but argument is of type ‘struct server *’
 int     ok_at_loc       (const char *file, int line, int test, const char *fmt,

so at least to me a pointer is false if null, otherwise true.  The documentation says implies a boolean, but the signature is an int.  Should it be a bool instead of int?  Should ok cast the test value?

**Comment by zorgnax** [comment]
you can cast it like `ok((int) s = server_init());` but I'll fiddle with the macro a bit to see if I can get it to work with no warnings. I'd like to get it to work the way you have it.

**Comment by allanwind** [comment]
On 2015-08-31 08:57:55, Jacob Gelbman wrote:
> you can cast it like `ok((int) s = server_init());` but I'll 
> fiddle with the macro a bit to see if I can get it to work with 
> no warnings. I'd like to get it to work the way you have it.

Yeah, I understand you can cast, but that unnatural.

The other libtab library
<http://www.shlomifish.org/open-source/projects/libtap/> uses a macro:

# define ok1(e) ((e) ?                                                  \
                 _gen_result(1, __func__, __FILE__, __LINE__, "%s", #e) : \
                 _gen_result(0, __func__, __FILE__, __LINE__, "%s", #e))

That other library requires you to use ok1() for single arguments, and ok() for
multi-arguments.  Your library is much nicer that way.


/Allan
-- 
Allan Wind
Yaxto - Runs My Business
<https://yaxto.com>

**Comment by zorgnax** [comment]
took me a while to get around to this, but, I was able to add an automatic (int) cast to the ok() macro. I can't do the other macro's (in any way that I know of).
