### ISSUE TITLE
Semicolon at end of cmp_mem macro

### ISSUE THREAD

**Issue by player1537** [zorgnax/libtap#28]
One of the features of this library is that it allows you to use the assertions as parts of `if` statements. e.g. 

```c
int rv = 1;
if (!cmp_ok(rv, "==", 0, "should return 0")) {
  diag("It didn't produce 0, that's bad");
}
```

This works great, except for the `cmp_mem` macro, because it is defined as:

```c
#define cmp_mem(...)     cmp_mem_at_loc(__FILE__, __LINE__, __VA_ARGS__, NULL);
```

There's a semicolon at the end, which means that you get a compile-time error if you try to do:

```c
if (!cmp_mem(actual, expected, length, "message")) {
  // Different
}
```

----

I believe this only needs that semicolon removed and it will work correctly.

**Comment by zorgnax** [comment]
Thanks. It definitely should be that way. I just didn't notice before.
