### ISSUE TITLE
Problem with ok macro

### ISSUE THREAD

**Issue by fmondello** [zorgnax/libtap#30]
I was using the ok macro to compare two pointer type variables, like this:

`ok(fff.call_history[0] == my_func, "blah_blah_msg");`

and it was causing the following warning from gcc:

../../../helpers/tap/tap.h:48:56: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #define ok(...)          ok_at_loc(__FILE__, __LINE__, (int) __VA_ARGS__, NULL)
                                                        ^
..//.build/test/tests_eppos_update_logic.c:79:2: note: in expansion of macro ‘ok’

Acording to the manual, you can use it to test anything that returns a true or false, but it is not the case.
The problem (I think) is the definition of the mentioned macro:

`#define ok(...)          ok_at_loc(__FILE__, __LINE__, (int) __VA_ARGS__, NULL)`

When the preprocessor expands the macro, you get this:

`ok_at_loc("file.c", 291, (int) fff.call_history[5] == EpposUpdate_InstallUpdate, "msg", ((void *)0));`

So it is casting a function pointer to int, then compare it with a pointer to function, which causes the warning shown above. The only way to eliminate the warning is to sorround the test with parentheses:

`ok( (fff.call_history[0] == my_func), "blah_blah_msg");`

It is fine as long as you compare ints, but in any other case, you need the parentheses.
Although not an issue per se, probably it would be great to add that recommendation to the documentation.

Hope it helps,
Fernando

**Comment by zorgnax** [comment]
thanks for pointing that out. I can never get these macros exactly perfect, but I want the way to deal with this problem a little nicer than to surround the argument with an extra set of parenthesis. so I removed the auto cast into (int). which will prevent warnings when using ok() on a true false variables or on expressions like foo == bar. if you are testing something like that a function pointer is not NULL, you may have to put a manual cast in there, to prevent the compiler warning.
