### ISSUE TITLE
use of plan() causes bool functions that don't return anything to work both as true and false

### ISSUE THREAD

**Issue by leavens** [zorgnax/libtap#31]
I have been using libtap in my Introduction to Programming with C class at UCF this semester. Overall we are very happy with it. Thanks!

However, students complained that for one of my test suites all the tests passed, even though they had no code in a predicate function (i.e., one that should return a _Bool). Of course, that is an incorrect implementation, but often students are omitting the return statement in a function, and so not detecting that is a serious problem when not detected. I was eventually able to find that the tests improperly passed in this manner only if the testing code called plan(). If the call to plan() is omitted, then the tests work properly, checking the return value.  I have boiled this down to the attached files, which I thiink clearly show the problem. This happens under Windows 10 using gcc (GCC) 5.4.0 running under cygwin and also under MingW gcc.

The attached zip file has 3 files. bfun.c has a Boolean-valued function named bfun in it that doesn't return a value. bfun.h is a header file for that. test_bfun.c has a main() function, which shows the problem. If you comment out the call to plan() in test_bfun.c, you get the expected detection of incorrect behavior in bfun().

[bfun-example.zip](https://github.com/zorgnax/libtap/files/888602/bfun-example.zip)

**Comment by zorgnax** [comment]
Thanks for using my library. I tried out the code on my Mac laptop and found some of the outputs to be consistent and others seem random. Which one’s which seems based on whether I call the plan() function. I guess that the return is taken might be taken from the last return statement seen or the local state of memory.

**Comment by leavens** [comment]
Hi Jacob,

Thanks for looking into it.  I wonder if there is some interaction with the
va_args mechanism used by ok() but I'm not competent to fix this, so I am
hoping you can figure it out.

        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens <http://www.eecs.ucf.edu/~leavens>
phone: +1-407-823-4758
        leavens@cs.ucf.edu <leavens@eecs.ucf.edu>
