### ISSUE TITLE
Please consider licensing as GPLv2+

### ISSUE THREAD

**Issue by autarch** [zorgnax/libtap#9]
The current license makes it incompatible with code under the Apache 2.0 license. Allowing version 2+ of the GPL would make it compatible.

**Comment by quentusrex** [comment]
Any chance to update the existing license, or to dual license to something compatible with GPL and non-GPL? Such as:
https://www.gnu.org/licenses/lgpl.html
or
https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html

Right now a piece of software that is licensed with MPL can't use libtap for testing framework. Moving, or adding an LGPL license should solve the issue for the full spectrum of software projects.
